class KeywordsLists
	attr_accessor :beacon_key, :rtbMacros, :sameParty, :priceFPList, :adCompaniesCat, :filetypes,:disconnect, :cookiesync, :types, :imps, :manualCats, :keywords, :inria, :adInParam, :rtbCompanies, :subStrings, :browsers
	
	def initialize(external,defs)
		@defines=defs
		@adCompaniesCat={"host.com"=>[]}
		@rtbMacros={
			"dsp"=>{"adnxs.com"=>"pubclick","mopub.com"=>"bidder_name","metamx.com"=>"bidder_name","w55c.net"=>"ei","mythings.com"=>"adnclk","taptapnetworks.com"=>"bidid", "mathtag.com"=>"3pck","qservz.com"=>"click3rd","contextweb"=>"cwu"},
			"adx"=>{"mediasmart.es"=>"exchange","w55c.net"=>"rtbhost"},

			"pubs"=>{"mopub.com"=>"pub_name","metamx.com"=>"pub_name","casalemedia.com" => "n", "rfihub.com"=>["pe","p"], "contextweb.com"=>["referrer","cwr"],"adnxs.com"=>"referrer","w55c.net"=>"s", "rtbfy.com"=>["domain","utm_source"], "taggify.net"=>["refdomain", "domain","utm_source"],"adsrvr.org"=>"td_s","ero-advertising.com"=>"document","amazonaws.com"=>"referer_url_enc","media.net"=>["requrl","domain"],"revsci.net"=>["referrer","domain"],"liverail.com"=>"url","moatads"=>"j","brandsmind.com"=>"ru"},

			"sizes"=>{"turn.com"=>"l","get.it"=>"size","contextweb"=>["cf","dm"],"mediasmart.es"=>"size","amazonaws.com"=>"creative_size", "moatads.com"=>"zMoatSZ","media.net"=>"size","taptica.com"=>"tt_size","technoratimedia.com"=>"sz"},
			"ssp"=>{"appflood.com"=>"ssp_name"},
			"position"=>{"moatads.com"=>"zMoatPS"}}

		@beacon_key=["beacon","adimppixel","pxlctl","1x1","1by1"]
	
		@filetypes={".avi"=> "video", ".doc"=>"text", ".htm"=>"html", ".html"=>"html", ".jpg"=>"image", ".jpeg"=>"image", ".png"=>"image",
					".bmp"=>"image",".js"=>"script",".css"=>"styling",".gif"=>"gif",".json"=>"data","xml"=>"data",".mpeg"=>"video",".txt"=>"text",
					".wav"=>"video", ".swf"=>"video",".mp3"=>"video",".mp4"=>"video",".ttf"=>"styling",".webm"=>"video",".webp"=>"image",
					".eps"=>"image",".ajax"=>"script",".midi"=>"video",".mid"=>"video",".mpg"=>"video",".tiff"=>"image",".php"=>"html",
					".woff"=>"styling",".mov"=>"video",".qt"=>"video",".asp"=>"html", ".jsp"=>"html", ".pdf"=>"text",".pixel"=>"image",
					".ppt"=>"text",".pptx"=>"text",".zip"=>"data",".rar"=>"data",".vlc"=>"video",".ram"=>"video",".zlib"=>"video",".pjpeg"=>"image",
					".dhtml"=>"html",".svg"=>"image",".woff2"=>"styling",".aspx"=>"html",".ashx"=>"html",".img"=>"image",".jsonp"=>"data",
					".csx"=>"script",".otf"=>"styling",".sjs"=>"script"}
		
		@types={"*" => "other", "none" => "other" ,"application/x-woff" => "styling", "application/font-woff" => "styling", 
			"application/font-woff2" => "styling", "application/javascript" => "script", "application/json" => "data", 
			"application/octet-stream" => "video", "application/vnd.ms-fontobject" => "styling" ,"application/x-font-ttf" => "styling", 
			"application/x-font-woff" => "styling", "video/mp4" => "video",
			"application/x-shockwave-flash" => "video" ,"application/x-www-form-urlencoded" => "html", "font/ttf" => "styling", 
			"font/woff2" => "styling", "image/bmp" => "image", "image/gif" => "gif", "video/webm" => "video",
			"text/plaincharset=utf-8"  => "text", "text/xml"=>"data", "font/opentype"  => "styling", "font/woff" => "styling" ,
			"no-cache" => "other", "application/x-font-opentype"  => "styling", "image/jpeg" => "image", "image/jpg" => "image" ,
			"application/xml" => "data", "application/font-ttf" => "styling", "application/hal+json"=>"data", 
			"application/x-font-truetype" => "styling", "application/x-gzip"=>"video", 
			"application/x-mpegurl"  => "video", "binary/octet-stream"  => "video", "content/unknown"=>"other", "video/x-msvideo"=>"video",
			"application/zlib"=>"video", "font/truetype"  => "styling", "image/" => "image", "text/x-js"=>"script", "video/mpeg"  => "video", 
			"image/pjpeg" => "image", "image/png" => "image" ,"image/svg+xml" => "image", "application/vnd.apple.mpegurl" =>"video",
			"image/webp" => "image", "text/css" => "styling", "text/css;" => "styling", "application/x-javascript"  => "script" ,
			"text/html" => "html", "application/ecmascript"  => "script", "font/x-woff"  => "styling",
			"*/*"  => "other", "multipart/mixed" => "other", "text/html-by-ajax" => "html", "application/x-font-otf"  => "styling" ,
			"text/javascript" => "script", "text/json" => "data", "text/plain" => "text", "text/x-json" => "data"}

		@imps=["impression","_imp","/imp","imp_"]

		@manualCats={"flix360.com"=>"Analytics","exelator.com"=>"Analytics","mythings"=>"Advertising","w55c.net"=>"Advertising",
			"gosquared.com"=>"Analytics","metamx.com"=>"Advertising","1dmp.io"=>"Advertising","antevenio.com"=>"Advertising",
			"madnetx.com"=>"Advertising", "mpstat.us"=>"Analytics", "gradientx.com"=>"Advertising","netmng.com"=>"Advertising",
			"akamai.net" => "Content","adap.tv"=>"Advertising","roixdelivery.com"=>"Advertising","roix.com.br"=>"Advertising",
			"akamaiedge.net" => "Content","akamaized.net" => "Content","akamaihd.net" => "Content","edgesuite.net" => "Content",
			"edgekey.net" => "Content","srip.net" => "Content","akamaitechnologies.com" => "Content","akamaitechnologies.fr" => "Content",
			"akamaitech.net" => "Content","akadns.net" => "Content","akam.net" => "Content","akamaistream.net" => "Content", 
			"createjs.com"=> "Content","alephd.com" => "Advertising", "ads.yahoo.com" => "Advertising", "igodigital.com"=>"Analytics",
			"dynamicyield.com"=>"Analytics","bootstrapcdn.com" => "Content","cloudflare.com" => "Content","tiqcdn.com" => "Content",
			"sonobi.com" => "Advertising", "semasio.net"=>"Analytics", "semasio.com"=>"Analytics","rhythmxchange.com" => "Advertising",
			"3lift.com" => "Advertising","triplelift.com" => "Advertising","eyeviewads.com" => "Analytics","rakuten.com" => "Advertising",
			"everesttech.net" => "Advertising","1nimo.com" => "Advertising","4dsply.com" => "Advertising","foresee.com"=>"Analytics",
			"4seeresults.com"=>"Analytics","9cdn.net" => "Content","afsanalytics.com"=>"Analytics","aidata.me"=>"Analytics",
			"advombat.ru"=>"Analytics","abtasty.com"=>"Analytics","albopa.work" => "Advertising","alicdn.com"=>"Content",
			"ani-view.com" => "Advertising", "answerscloud.com"=>"Analytics","apester.com" => "Content","arcpublishing.com" => "Content",
			"arecio.work" => "Advertising", "publited.com" => "Advertising", "arkadiumhosted.com"=>"Content","aspnetcdn.com"=>"Content",
			"audiencemedia.com"=>"Content","bannerflow.com" => "Advertising","beanstock.com" => "Advertising","yashi.com" => "Advertising",
			"bleacherreport.net" => "Content", "active-agent.com" => "Advertising", "affec.tv" => "Advertising", "dpclk.com" => "Advertising",
			"angsrvr.com" => "Advertising", "bidswitch.net" => "Advertising",  "bidswitch.com" => "Advertising", "fidelity-media.com" => "Advertising", 
			"ibillboard.com" => "Advertising","kavanga.ru" => "Advertising", "hgads.com" => "Advertising", "smartstream.tv" => "Advertising", 
			"univide.com" => "Advertising","acxiom-online.com" => "Analytics", "dianzicheng.club" => "Advertising","gradientx.net"=>"Analytics", 
			"beanstock.co" => "Advertising", "hstpnetwork.com" => "Advertising", "beatchucknorris.com" => "Advertising", "metrigo.com" => "Advertising",
			"bidr.io" => "Advertising", "bidtellect.com" => "Advertising", "bidtellectual.com" => "Advertising", "adgrx.com" => "Advertising",
			"blogsmithmedia.com" => "Content","blueconic.net"=>"Analytics","blueknow.com"=>"Analytics","bnc.lt"=>"Analytics",
			"branch.io"=>"Analytics","centro.net" => "Advertising", "brand-server.com" => "Advertising","brealtime.com" => "Advertising",
			"bttrack.com" => "Advertising", "burt.io"=>"Analytics","clickagy.com"=>"Analytics","cloudzonetrk.com"=>"Analytics",
			"cnt.my"=>"Analytics", "track.e7r.com.br"=>"Analytics", "tracker.bt.uol.com.br"=>"Analytics", "isuba.s8.com.br"=>"Content",
			"iacom.s8.com.br"=>"Content", "metrics.uol.com.br"=>"Analytics", "clearsale.com.br"=>"Analytics","amobee.com"=>"Analytics",
			"clearsalesolutions.com"=>"Analytics","connatix.com" => "Advertising", "connexity.net"=>"Analytics", "ophan.co.uk"=>"Analytics", 
			"cxpublic.com" => "Content","dataradar.es" => "Content","delicious.com" => "Content","directclicksonly.com"=>"Analytics", 
			"dmcdn.net" => "Content","cm.dpclk.com"=>"Analytics","dynad.net" => "Advertising", "edgefonts.net" => "Content",
			"elasticad.net" => "Advertising","fastly.net"=>"Content","freegeoip.net"=>"Analytics","gannett-cdn.com" => "Content",
			"gdmdigital.com" => "Advertising","genesismedia.com" => "Advertising","georiot.com"=>"Analytics", "geni.us"=>"Analytics", 
			"go-mpulse.net"=>"Analytics","apis.google.com"=>"Content","accounts.google.com"=>"Content","gg.google.com"=>"Analytics",
			"goroost.com" => "Content","gssprt.jp" => "Advertising","heatmap.me"=>"Analytics", "heatmap.it"=>"Analytics", "meltdsp.com" => "Advertising", 
			"hi-mediaserver.com" => "Content","hotjar.com"=>"Analytics", "hwcdn.net" => "Content","iadbox.com" => "Advertising", 
			"impdesk.com"=>"Advertising","imrk.net"=>"Analytics","ipredictive.com"=>"Advertising","ixiaa.com"=>"Analytics", "stickyadstv.com" => "Advertising",
			"janrain.com"=>"Analytics","janrainbackplane.com"=>"Analytics","jquery.com" => "Content","jquerytools.org" => "Content",
			"jsdelivr.net" => "Content","justpremium.com" => "Advertising","jwpcdn.com" => "Content","jwpsrv.com" => "Content",
			"lomadee.com" => "Advertising","madnet.ru" => "Advertising","madnetex.com" => "Advertising","marfeel.com"=>"Analytics",
			"matheranalytics.com"=>"Analytics","media-imdb.com" => "Content","mediavoice.com" => "Advertising","polar.me" => "Advertising",
			"medium.com" => "Content","micpn.com"=>"Analytics","movableink.com"=>"Analytics","video.microcontenidos.com" => "Content",
			"mkbwlcdn.com"=>"Analytics","ml314.com"=>"Analytics","bombora.com"=>"Analytics","mmondi.com" => "Advertising","scanscout.com" => "Advertising",
			"krxd.net" => "Advertising","nr-data.net"=>"Analytics","newrelic.com"=>"Analytics","omnitagjs.com"=>"Analytics","glispa.com" => "Advertising",
			"optimatic.com" => "Advertising","pagefair.com"=>"Analytics","perfectmarket.com"=>"Analytics","taboola.com"=>"Analytics",
			"performgroup.com" => "Content","petametrics.com"=>"Analytics","pippio.com"=>"Analytics","polarmobile.com" => "Advertising",
			"postrelease.com" => "Advertising","nativo.net" => "Advertising","premiereinteractive.com" => "Advertising","tremorvideo.com" => "Advertising",
			"pressdisplay.com" => "Content","proxistore.com" => "Advertising","pubnative.net" => "Advertising","pubted.com" => "Advertising",
			"qmerce.com" => "Content","qualtrics.com"=>"Analytics","rackcdn.com" => "Content","rackspacecloud.com" => "Content","applift.com"=>"Analytics",
			"qubitproducts.com"=>"Analytics","realtime.co" => "Content","renr.es" => "Content","revee.com"=>"Analytics","videohub.tv" => "Advertising",
			"richmediastudio.com" => "Advertising","richmetrics.com"=>"Analytics","burtcorp.com"=>"Analytics","smaato.net" => "Advertising",
			"sekindo.com" => "Advertising","sharethrough.com" => "Advertising","simplereach.com"=>"Analytics","siteblindado.com" => "Content",
			"solvemedia.com" => "Advertising","sonataplatform.com" => "Advertising","spingo.com" => "Content","stackadapt.com" => "Advertising",
			"stats.com" => "Content","sub2tech.com"=>"Analytics","sumologic.com"=>"Analytics","taboolasyndication.com"=>"Analytics","dynadmic.com" => "Analytics",
			"tagsrvcs.com"=>"Analytics","tailtarget.com"=>"Advertising","taptapnetworks.com" => "Advertising","liverail.com" => "Advertising",
			"zanox.com" => "Advertising","scmspain.com" => "Advertising","schibsted.es"=> "Advertising", "254a.com"=> "Advertising","dyntrk.com" => "Analytics",
			"gltrkk.net" => "Analytics","sponsorpay.com" => "Advertising","fyber.com" => "Advertising","epartner.es" => "Advertising", "affili.net" => "Advertising",
			"himediagroup.com" => "Advertising","himediads.com" => "Advertising","himediatech.com" => "Advertising","adux.com" => "Advertising",
		}

		@cookiesync=["match","sync","cm","csync","cm.g.doubleclick.net"]

		@keywords=["price","pp","pr","bidprice","bid_price","bp","winprice", "computedprice", "pricefloor",
			           "win_price","wp","chargeprice","charge_price","cp","extcost","tt_bidprice","bdrct",
			           "cost","rtbwinprice","rtb_win_price","rtbwp","bidfloor","seatbid","price_paid","maxPriceInUserCurrency"]

		@inria={ "rfihub.net" => "ep","invitemedia.com" => "cost",#"scorecardresearch.com" => "uid" 
				"ru4.com" => "_pp", "adsrvr.org" => "wp", #"tubemogul.com" => "x_price"  
			"pardot.com" => "title","tubemogul.com" => "price",
			"adsvana.com" => "_p", "doubleclick.net" => "pr", "ib.adnxs.com" => "add_code", 
			"turn.com" => "acp", "ams1.adnxs.com" => "pp",  "mathtag.com" => "price",
			"youtube.com" => "description1", "quantcount.com" => "p","rfihub.com" => "ep",
			"w55c.net" => "wp_exchange", "adnxs.com" => "pp", "gwallet.com" => "win_price",
			"criteo.com" => "z","casalemedia.com"=>"cp"}

		# ENHANCED BY ADBLOCK EASYLIST
		@subStrings=["/Ad/","pagead","/adv/","/ad/",".ad","rtb-","adwords","admonitoring","adinteraction","/ads","videoads",#,"ads/",
					"adrum","adstat","adviewtrack","adtrk","/Ad","bidwon","/rtb","admantx/","adclick","_ad/","/promos/"] #"market"]	

		@rtbCompanies=["adkmob","green.erne.co","mathtag.com","rubiconproject","bidstalk","openrtb","eyeota",
				"ad-x.co.uk","startappexchange.com","atemda.com", "advertising.com", "openx.net","adnxs.com",
				"gwallet.com","tubemogul.com", "ru4.com","turn.com",
				"qservz","hastrk","clix2pix.net","exoclick","adition.com","yieldlab","trafficfactory.biz","clickadu",
				"waiads.com","taptica.com","mediasmart.es","doubleclick.net","adsvana.com","criteo.com","adsrvr.org",
				"pardot.com","invitemedia.com","ads.yahoo.com"]

		@adInParam=["ad_","ad_id","adv_id","bid_id","adpos","adtagid","rtb","adslot","adspace","adUrl", "ads_creative_id", 
				"creative_id","adposition","bidid","adsnumber","bidder","auction","ads_",
				"adunit", "adgroup", "creativity","bid_","bidder_"]

		@browsers=['dolphin', 'gecko', 'opera','webkit','mozilla','gecko','browser','chrome','safari']


		@priceFPList=["elpais.com","cr9.party","currentlyobsessed.me","quantcount.com","taggify.net","gradientx.net",
			"brazzers.com","ilius.net","hm.com","gameforge.com","dogpile.com","info.com","baidu.com","brandsmind.com",
			"infospace.com","famehosted.comforo20.com","nanigans.com","webcal.fiyhd.com","zalando.es","forociudad.com",
			"01net.com","110school.ru","115animal.com","1201gaming.com","123chs.com","123internet.gr","126.net","12iacc.org",
			"15fgeeb88.com","15minute-paydayloans.co.uk","2525menkyo.com","2playergames.co.nz","33b.mobi","33b.ru",
			"3palms.ch","3show.biz", "50webs.com","51cto.com", "55club.cn","56k.us","7gamers.com.au","abimbolajunaid.org",
			"9555.xn--p1ai","aaa.yt","aanorthflorida.org","aareklama.ru","aaronveryard.com","abdullahshwaikah.com",
			"abnamrobank.ca","a-body.net","aboutthedomain.com","aceitar.co","ach22.ru","acpcwc.org","actiondecareme.ch",
			"activezeroenergy.mobi", "actupbasel.org","acuityplatform.com","ad2links.com","additionplus.com","adgo.by",
			"admedicine.org","adm-socially-stage.com","adoption.com","adorablebabyanimals.com","adriangrosser.de",
			"adsmrkt.com","advenbbs.net","almouna.org", "almubassir.com","avtox.net","ayland.ru","ebay","3jedareh.com",
			"adwin.com","aecoimbracentro.pt","aerial.dance","aeromodelismovirtual.com","aeropostale.com",
			"africandrummingtownsville.com","afro360news.com","afrohelse.no","agenciaorigem.com.br","infospace.com",
			"aiellocalabro.org","aisyiyahkotakediri.org","aktive-fans.de","al5hatib.com","alaskajournal.com",
			"albinoblacksheep.com","al-daa.com","al-dalel.com","alepouditsa.gr","allcrimea.net","allencountygop.com",
			"altecaluminio.com.br","alternatehistory.com","alternatehistory.org","altrarovereto.it","7ba.biz",
			"alvsjomiljorad.se","amatube.eu","ambig.com","amlakyousefi.com","anambrayouthsassociation.org",
			"ancestry.com.au","andrepires.net","androidcv.com","angelencountervideos.com","animando3d.com",
			"animeshko.ru","annikalangvad.dk","anoprienko.com","antichat.ru","antondanielsson.se","anumex.com",
			"api-01.com","apkthing.com","appropedia.org","apvrovra.in","aratingaja.info","arayeshsepideh.com",
			"arcadiafloresville.mobi","arkresidential.mobi","arousshow.com","artisticalstudios.com","aryohadi.com",
			"asafesite.com","asahi.com","asesoramosonline.com","asolfsskali.is","attorneysdot.net","auctionserver.net",
			"aught.jp","augies-place.com","aurakikoto.hu","auto-t.ru","avhsalumni.org","avindar.net","avradinis.gr",
			"ayqingenieros.com","b2fireflies.com","babatemple.org","badcaps.net","bahrainstrategiccenter.org",
			"baiduyun.me","bailefelix.net","bali-99.com","bali-99.com","balletshmallet.com","bangaloretdpforum.com",
			"barbarian-games.com","bariskina.ru","baseruralconsultoria.com.br","baxta.com.au","bbwurls.com","bdsm-zone.com",
			"beaba.info","beartales.me","beautyassociation.org","beckertalk.com","beefit.ir","belkhiria.net",
			"belongsinamuseum.com","bel.tr","benhofgroup.com","biceliyiz.biz","biddingx.com","bidhopper.com",
			"biegowkiwesola.org","bienesymaquinaria.com","big-nose.com","bildungswelten.info","binary-trading-video.com",
			"binjiangguoji.com","birdflyinsky.com","bit-multimedia.com","bizland.com","biztechskopje.com","000a.biz",
			"blablaland.com","blackdecor.ir","blackpointforum.com","bluefly.com","bmu.fr","boarderking.it",
			"boardreader.com","boat.ag","boatdealers.net","bodyzmbalance.com","bokharaco.com","bokmassan.se",
			"bonstempos.pt","bookmerken.de","bookmrk.us","boshcraft.com","boxpicks.com","brasanddrawls.com",
			"braveblog.com","bravenet.com","brimoto-group.co.uk","brokenbay.org","brookshiredental.com",
			"bruenefeld.de","bspindonesia.com","buddylead.com","buenapark.com","bugamark.com","bugi.ch",
			"bullseyesport.com","bullshido.net","businesscatalyst.com","businessplaymate.com","buslaev.ru",
			"by616.com","cablel.ro","cafemagellan.no","california-security-guard-card.com","caminoplata.com",
			"cancionesdetelenovelas.com","carissaputri.com","casadaeira.org","casadellibro.com",
			"casertasette.com","cassandra2.com","catholique.fr","caxapok.kz","cceresearch.com","cdco07.fr",
			"cehcharlotte.com","cellebiz.com","centerfish.ru","centili.com","ceramicasferret.com",
			"ceres21.org","cgia.us","ch0p.me","charite-bioinformatik.de","charlestonbattery.com",
			"charlestonretirement.net","chatakorbielow.pl","chathouse3d.com","chebup.com","chevrim.com",
			"chicagoscubaschool.com","childpsy.org","china-nh.com","chinood.ir","choice-ny.com","chromecoaster.com",
			"ci123.com","cidadedeluanda.net","cifconsultor.com","cinemaklub.ru","cityblm.org",
			"cityofbartow.net","cityofcashmere.org","cityofvacaville.com","citystudios.se",
			"clanstruchhi.com","classicshop.com.br","clinmedres.org","cmckorea.org","cmsfarsi.net",
			"cncyiling.com","cnujsrh.com","coachpattyusa.net","codsana.com","cogonline.net","co.il",
			"cojinesterapeuticos.com.mx","comfortplusacheating.com","comfortwarrior.com","com.ng",
			"com.nu","com.pe","com.pl","compraenquart.com","com.tr","com.tt","comunicadoressf.com",
			"conaxtechnologies.de","conceptproductionz.com","concreteinstitute.com.au","confirmit.com",
			"consolewars.de","constructionnews.co.nz","cookinggamesfun.com","cool-hdwallpapers.net",
			"cornflakes3d.com","cort.as","corvallisoregon.gov","costamesaca.gov","co.th","co.ua","co.ug",
			"couponyield.com","cpt-co.com","crazy-games.eu","creationpointdecroix.com","creativecdn.com",
			"crimson-head.com","croet.com","cruiselinesjobs.com","csalazar.org","cssoc.co.uk",
			"csusmhistory.org","ctassist.com","ctwins.com.br","cuahangvanphongpham.com","cult.cu",
			"cunysportsreport.com","curlingzone.com","custeel.com","cw.cx","cwsurf.de","czdesign.ca",
			"danesh-afagh.com","danicapatrick.uk","danzanet.org","darinelly.com","darkvillains.com.br",
			"dashti10.ir","datab.us","datahub.io","davidicke.com","dawanda.com","dawnbreaker.com",
			"deadsea-beach.com","deathcontrol.de","dechaleira.com","decorativemodern.ir","dedecms.com",
			"dedibox.fr","denalimasonry.com","derstandard.at","desertflor.com","designdogs.net",
			"designperlacasa.it","destinationdominica.org","devatics.com","dewitt.at",
			"diabetesforums.nl","di.al","diamondfest.com.br","dicoperso.com","dieselpowerconnections.com",
			"difesadelsuolo.it","digitvinfo.es","digtenu.dk","diigo.com","dimensioneautobacoli.com","di-nisio.de",
			"dipyourcar.com","discusslinks.com","disney.co.uk","distanakpacitan.org","distro.cl",
			"djsirpee.com","djstixxx.be","dlasmoras.com","docall.biz","doc.gov","documentroot.com",
			"dofcoffee.com","dogengine.com","dojin.com","domes-dos.de","dom-kedra.ru","doris-schlee.de","doyoukiss.com",
			"dreamdemons.net","drustvo-ravnateljev.si","dsscteam.com","dtnt.info","dubai2iran.com",
			"dveri-clin.ru","dzagi.com","eagleweb.xyz","earthdemo.com","easpiattaforme.it","easytestbook.com",
			"eburgclub.ru","echodrama.net","economicstressindex.com","edesk.jp","edublogs.org","edu.bo",
			"educatedbyerrors.de","edu.ec","edu.ng","edurm.ru","edu.ru","effelunga.net","egipto.com",
			"egoruntulusohbet.com","egpet.net","ekspertbudowlany.pl","elearningnews.net","electrocomponents.com",
			"elenacuadrado.com","elettraautomazioni.com","elforocristiano.org","elijahadamband.com","elite-sports.ru",
			"elleryhomestyles.com","ellwoodcanyonfarms.com","elrapado.com","elynx.nl","emailretargeting.com",
			"emrysdesigns.com","energysolutions4you.com","epicor.com","ereadernation.com","ero-advertising.com",
			"escueladefinanzasreal.com","esearch.ru","eshgh-20.tk","eso-wiki.org","esquizopedia.com",
			"estimatedwebsite.es","etece.es","etiquetasexpress.com.mx","evansvilleapc.com",
			"eventful.com","evobsol.com","evolve-worldwide.com","excursionesproviatur.com","extrasait.ru",
			"ezbbs.net","ezebee.com","fanbase.com","fansub.tv","fantasiediariel.com","farmbaskit.com",
			"fashionspot.ro","fastenopfer.com","fatcountry.com","fbcdurant.org","fcpe34.org","feber.es",
			"fgn-guild.com","fidespesetamor.com","figaroenzo.de","fightsol.com","filmdatabase.dk",
			"fincen.gov","finecooking.com","firstchoicecu.org","fitile2.com","fjbnwy.com","flashbored.com",
			"flyingelephantuae.com","food-dog.ru","foodservicenews.net","fordoo-gypsum.com",
			"forexsoul.com","formacionyoficios.com","forumbiodiversity.com","forumciclismo.net",
			"forumerz.com","fotodimension.com.ar","fotonesta.com","foxtrot-international.com","francemetal.com",
			"frankeltutors.com","franslivre.net","fraudnet.info","freakytrigger.co.uk","freehostia.com",
			"freehost.pl","frenadesonoticias.org","frenzee.org","frontrowlingeries.com","fuckurgf.com",
			"fullybookedonline.com","fundacaonokia.org","fungaiolisiciliani.it","funlix.de","funtastic-party.de",
			"fuu8.com","fzhufu.com","g99games.com","gabrielcds.net","gag.pw","galaxyrc.es",
			"galeriedon.com","game-baby.net","gamecookie.com","gameloft.com","gamersyard.com",
			"gamingbasement.com","gangsterparadise.co.uk","gapeland.biz","gastroclinicaan.com.br",
			"gatzgatz.com","gc-gip.ru","gcmforex.com","gemssensors.com","genanalalban.com","geofilmebi.in",
			"geo-samyaro.com","gerakanaktif.com","german-chinese.eu","gerva.lt","ggo.vn","gilgameshsecurity.com",
			"giochaviet.com","giochigratis.info","glink.jp","globalalsocialnetwork.com","globat.com",
			"globo.com","glum-shop.ru","go4shop.vn","goingviralposts.net","goku-games.com","golawphuket.com",
			"golpluksut.com","gonulpervaneleri.org","goodreads.com","goodtime.ir","goodtofu.org",
			"goshootinggames.com","go.th","gotop100.com","gov.cn","gov.tr","gov.uz","gowhiteboardhighered.net",
			"goxl.me","graecusterra.ru","grandsolarinc.com","grassrootdevelopmentinitiative.com","gratisplay.it",
			"grepolis.com","gr.jp","growswedes.com","grupo-cpi.com","gtheatingltd.co.uk","gti16.com",
			"gtradersoftware.com","guate360.com","guayaco.com","guiafast.com","guildwars2.com",
			"gulfindustryfair.com","gymnasticscrosstraining.com","h1z1hq.com","hauori.com","hausfrauen-ganz-privat.de",
			"h-a-z.org","headstats.com","healing-handssanctuary.co.uk","healthybodyspot.com","heavyhosts.com",
			"heimishchat.com","hellotranny.com","herosjourneyrpg.com","herters-hun.de","hideurl4you.com","hidn.com.au",
			"hillsessay.com","hilltopperalumni.com","hitag.pt","hitmuzik.ru","hk-eg.org","hobbit1.info","hofzakelijk.nl",
			"holierthanthou.org","hollywood43.ru","hornes.org","hostel108.ru","host-h.net","hotelrealestatenews.com",
			"housingdata.org","houstonlimolinks.com","hprlnk.ru","htmklaverjas.nl","humingpeng.com","humsitaray.tv",
			"hundekrankengymnastik-kraus.de","hune.com","hyperdrivei.com","i-altai.ru","iandagroup.com",
			"ibbycongress2014.org","iberfit.pt","ibis21.info","idealmaxsolution.com","ideatutoring.org",
			"idforum.org","idg.com.au","ifokus.se","igrejaprogresso.com.br","ikpa-usa.org","iksv.org",
			"ilbarone.de","ileaxepandalaira.com.br","imagevenue.com","immobiliensanierung-amboss.de","imozaic.com",
			"imusinstitute.net","indiaserver.com","info.pl","informe16.com","informeproductora.com","informus.se",
			"infoturcuba.cu","in.gov","inkey.in","in-memory-of-you.com","innokmg.kz","intcommerce.co.uk",
			"internationalsexguide.info","involved-gaming.com","ioffer.com","ipc-chicago.com","lagonaki.com",
			"ipswichalebrewery.com","iptorrents.com","ira.li","iraqiyeen.com","iriscatering.no","iris-web.com",
			"isafacts.com","isa.ru","iscaguadeloupe.com","iscleaner.com","iscool.pl","isenturk.com","is.gd",
			"isggroup.eu","iskra-orsk.ru","isolar.com.mx","italkursy.ru","itechol.com","itesin.cz","ithink.pl",
			"itprobit.com","itsyurl.tk","ivpc.org","iwebreader.com","iwix.net","iwt.pl","izmail.es","jalaan.com",
			"jamp.gr","janimakinen.com","jhku.net","jjsapido.com","jnbridge.com","joerg-sachse.de","jonfelix.net",
			"joshaaronwood.com","jsycgx.com","juegosdemariobros.tv","juegosdevestir.co.uk","jumbobbs.com",
			"justusboys.com","k12educationtips.com","kadangcoffee.com","kaktusit.com","kanaken.net","kannikar.com",
			"karelawyer.com","katdev-development.com","katstron.pl","kavkazinfo.net","kayoobi.com",
			"kekenet.com","kelchambredhotes.fr","kelurahansungaibesar.info","kenyans.us","keralasbelleza.es",
			"keymachine.de","khasanahminang.com","khilmashkri.org","kickoffcoverage.com","kidssofashop.com",
			"kinghost.net","kisaltiyor.com","kit.edu","klankbordcmd.nl","kleintjesgoed.be","knyajna.com","metarss.com",
			"koatsystems.com","kobec.org","koleksix.com","kompass.com","komsol.se","koperasiadil.com","koppelgoor.nl",
			"kotori.me","krakataujogja.com","krxd.net","ksac.co.kr","kus-jambi.com","l5l5.net","lafranceapoil.com",
			"lanthrax.com","larednetwork.com","lastwagenspiele.com","latinchat.com.mx","latinchatnet.com",
			"lavega.cz","law-region.ru","laylayhome.com","lboiteux.fr","leadsystemnetwork.com","leatherjourney.org",
			"leben-mit-ms.de","lebenzitate.com","legacyrecordings.com","lemimosesportland.it","lengow.com","leos-berolina.de",
			"lernen-top100.de","lesprixducoin.com","levautomacao.com.br","levigxi.com","liblit.com","libsyn.com",
			"lifestylebloggo.de","lighterthanairamerica.com","lighthouseexecutives.com","lightingcontrolsassociation.org",
			"lihebo.com","limasollunaci.com","lindsaysfurniturerc.com","lineamundial.com.ar","linkhoster.com","linkopp.net",
			"linksdepot.net","literatinagyferenc.hu","liuzigu.com","liveinfitness.com","ll2.de","lnkeg.com","logis.im",
			"loqal.no","louisianafresh.com","lovedwell.com","loveformusic.it","l-training.ch","luccasocialandgames.com",
			"luigjes.com","lviv.ua","lzjl.com","m10086.info","mabil.ca","madberry.org","mails2.net","mamaedirce.com.br",
			"mammitzsch.com","maneraprivada.eu","manthanarts.com","manuelromeroifbbpro.com","marianum.eu",
			"marionhansen.de","maripuente.com","martialink.co.uk","masireagahi.com","massotherapieadomicile.ca",
			"masterdesigns.co.uk","maximusart.rs","maxrank.org","mayanrocks.com","mb.ca","mcfc.pl","mental-yoga.org",
			"medanorganik.com","media-pgri.com","mediapointds.com","mediav.com","meetmyshops.com","memorydropbox.ca",
			"megadelfi.com","megasun.md","megatona.net","mehmettourism.com","mellow-mushroom.com","merawatpenyakit.com",
			"merchandising.ru","mesjeuxdefilles.com","metalyzer.com","meta-ua.com","metropolitan-decorating.com",
			"mezatforum.com","mgutm.ru","mhsalumniassoc.org","michaelbrownsuccesssystem.com","michigan.com",
			"microchip.com","midnitemusic.ch","migashco.com","mihokos21grams.com","mikebi.ru","milanuncios.com",
			"militaryhq.com","milujuhovezi.cz","mincultri.ru","minecraftfreeversion.com","minecraftgameonlinefree.net",
			"minidetector.com","mip-eg.com","mix.dj","mjjcommunity.com","m-learn.eu","mmfeist.de","mmorpg-net.net","mmr.ua",
			"mnaidsproject.org","mndsoft.com","mn.us","modalibri.it","modasvet.ru","modthesims.info","moe.ma",
			"montrealgazette.com","morbits.net","morningstar.se","morrissey-solo.com","moteur.ma","motors.co",
			"mountprospect.org","movies-corner.com","movistar.es","mrszinkowsclass.com","msharetips.com",
			"msus.me","mt27.co.id","mtqmexico.com","mulangsari.com","multibodymujer.com","muria.co.id","muzby.net",
			"muzmax.ru","myarcadeplace.com","mycallroom.com","mycapitaltv.com","myf1racing.com","nowoscimp3.pl",
			"mylittleponygamez.net","mysatoristudio.com","mysnowwhiteteeth.com","mywebstorage.de","myxbox.net",
			"na.by","nadiaemelia.com","nagalanddirectory.com","najvayeghalam.ir","nanapan.net","napavalleyduo.com",
			"nasa.gov","nashi-progulki.ru","nationalcityca.gov","navaraclub-thai.com","nawcc.org","nazwa.pl","nd-graphics.de",
			"ndyz.cn","needtoclick.me","neogaf.com","neska.lt","net.pl","neurostar.com","newmvs88.com","newmvs88.com",
			"newportbeachca.gov","new-potolok.ru","newprotect1.com","newsoft7.ru","newsvine.com","newtechschool.com",
			"nicholecheza.com","nichost.ru","nickymagnummedia.com","nieuwsflitser.nl","nisinetworks.de","no5hair.co.uk",
			"nolbune.net","northparkresidences-booking.com","noticiasabc.com","novonordisk.ch","novonordisk.fi",
			"npgfoundation.org","nuevorumbo.net","nukecops.com","nusantarawebsite.com","nutritionforum.com",
			"nytitanwrestling.com","observatoiredescomores.com","offalygates.com","office-kakehashi.com",
			"oldiestation.es","olgamebel.ru","olsonpages.com","olympe.in","omanex.com","omoshiro-news.com","ondeweb.in",
			"on.gt","onlinehome.fr","onlinehome.us","oops.jp","opalubka-center.ru","open-realty.org","opera7.jp",
			"optimumbeton.eu","orain.org","orainyphotography.com","oralpin.com","org.au","org.in","org.mt","org.sv",
			"org.uk","origitea.ru","orijan.com","orionresearch.org","orugacreativa.com","oswik.com","ourcoolvillage.com",
			"outdoornews.com","ozarks.edu","ozerysport.ru","p93.us","paceadvantage.com","padeltraining.com",
			"pakchemical.com","palmantics.com","pandawillforum.com","panduankita.com","paradaanimal.com.br",
			"parcero.net","parc-w.info","pa-s.de","pastelariabusiris.com","pasulukanlokagandasasmita.com","patriciaamaya.com",
			"paulabanks.com","pa.us","pavimentosarquiservi.com","pdtgroup.info","pearsoned.co.uk","pegpropgroup.co.uk",
			"pensiunegorj.ro","percussioneducationonline.com","perfectnakedgirls.com","personcounty.net","petrastdpc.com",
			"phpsns.com","phwattana.com","pijatanstudio.com","pilotinfo.cz","pilulo.us","pingnw.com","pinoysarisarilah.com",
			"pistonbay.com","pivovrazliv.ru","pixnet.net","pixtac.com","plateforme-xgh.com","platingmbh.de",
			"playgungames.net","pleaselandhere.com","pmituban.com","pnpd.co.uk","pobieralnia.org","poetrysplash.com",
			"polressimalungun.com","polynesia.tk","pomoc-zwierzakom.pl","portail2.com","porteno.net","powdertechcorby.co.uk",
			"powerlines.ru","pozinsurance.com","ppcu.org","prazdnichnyymir.ru","premium72.info","profieye.com",
			"productosnaturalesyartesanalesfincachipitlan.com.mx","proficup.ru","profwebcenter.ru","projectavalon.net",
			"projectbodybuilding.com","promoteboard.com","prom.ua","promusichandbook.net","prop2go.mx",
			"prostateimplant.com","p-spa.ru","ptland.jp","puertasdelamarina.com","puertasdelamarina.net",
			"puertaslasabina.com","pungi-cumparaturi.ro","pytkowski-art.com","qaradawi.net","qd-yuanyuan.com",
			"qee.jp","qflny.com","qr.net","qtrace.org","quadrantcenter.com","racbeecroft.com","radiationvibe.com",
			"radioactiva997.com","radioclub.es","railroad-x-forum.com","raul.gallery","rbbs1.net","rcfc.de","reachfld.com",
			"realestateschoolofsc.mobi","redandwhiteproductions.com","redenovatv.com.br","redhawkassociates.mobi",
			"refhius.com","reiat-theater-stetten.ch","renamed-gaming.de","replicawatch-store.com","rerolled.com",
			"rightkorean.com","rion-service.co.jp","roboguardalarms.com","scribd.com","scrapmetaltalk.com",
			"rockstah.com","rodelclub.li","rodoangeltravel.com","rosaceagroup.org","rotaryinternational.lv",
			"rsclasses.org","rsclassic.us","rtbassociates.com","rtmatic.net","rtwilliams.co.uk","rubenrubio.mx",
			"runte-marsberg.de","ruri2.com","rvlx.us","rv.ua","rwdake.com","sachdochoi.com","serveradvance.ru",
			"sadieberry.tk","saeedpazoki.info","safe.mn","saham2.com","sainttheresemustangs.com","sakura-boo-boo.jp",
			"sales-frontier.com","sanalda1numara.org","sandiegocustommotorcycles.info","sanihon.com","sanpai-web.com",
			"santeck.eu","sassyinfotech.com","scandesigns.dk","scaredsh-tlessthemovie.net","schoolpedagogy.org",
			"sck.dk","scoop.it","scottblairinteriordesign.com","scout24.com","sda-ilijas.ba","searchamateur.com",
			"secretlabtech.com","sedonaaz.gov","seesaawiki.jp","seil.la","sellhaironline.com","semanariolocal.cl",
			"semprainyeccion.com","sendbuttonprofits.com","seoportal.ro","seozeng.com","sepehrcar.com","sf311.org",
			"ser2master.science","seraiki.net","serambibisnis.com","sergiogameplayer.com","servis-autoplus.com","sfdhr.org",
			"sfgovtv.org","sfwater.org","shanasfashions.net","sharenotes.net","sharetheroadsafely.gov",
			"sharkbusinessconnection.com","shark-games.net","shiras.org","shivnee.com","shopatron.com",
			"shopcheck.ch","shopping-tirol.at","shopwiki.es","shorl.com","shortlinki.com","shstezpur.com","shtork.in",
			"sictra.no","siemaco.ch","sigames.com","sigarashow.com","sigarashow.ru","simars.ru","simplehealthnh.com",
			"simpleloveadvice.com","simple-server.com","sinarharapancutterindo.com","sinfoniettapolonia.pl",
			"sites4teachers.com","schylling.com","revakliev.com","thewebreport.com","thexrapp.com",
			"sjrcenter.org","skelbiu.lt","sketch-bd.com","skypixel.ir","slav-yard.ru","sleepingbeauteez.com","slideshare.net",
			"slutswifes.com","smalapala.com","smarterasp.net","smirajasthan.org","smka.org","smoothiesbeautyclinic.co.uk",
			"smsh.me","snopes.com","snowfactory.com","snuf.it","soccerprofoot.com","socialseolist.com","sofasetc.net",
			"softpart.ru","sogou.com","soporte-movil.com","so-ten.jp","sottel.ru","sourceforge.net","soyanews.info",
			"speckom2.ru","spielberg-double.com","splendidhotel.ru","sportman.by","sptgeotecnia.es","stabx.net",
			"standardminingcompany.com","standrewscricketclub.co.uk","startingmma.com","steamcommunity.com",
			"stepbystep.by","stephenakintayo.com","stm-gamers.com","storemax.com.au","streetfire.net","strictlytuition.com",
			"strongriver.com","stroycom53.ru","suachuamavach.com","sun63.ru","sunsetalgarve.com","supermulticolor.com",
			"svartekunst.no","swrpgnetwork.com","sxsly.com","synantisis.eu","systempardazgil.com","takoora.com",
			"talkreviews.com","talkreviews.com","tanculkovo.sk","taratsidis.gr","taringa.net","taxpolicycenter.org",
			"td-uslovaja.ru","teachipr.com","technewsbd24.com","techyworld.in","teiling.ch","teko-shop.ru","telediez.com",
			"telepolis.pl","teletronltd.com","telugutvtalkies.in","temprana.pl","tenshin-ryu.co.uk",
			"tepozmapa.com","terabytestudio.com","teropongumsu.co","tgcostruzioni.it","tgirltrack.com","thaidogcenter.com",
			"thailandqa.com","thaimeboard.com","thaipinoy.com","theabundancegroup.co","theeradej.com","thefactorygadsden.com",
			"thegioicuanhua.vn","the-horror.com","thenewhot.com","therachelswanfund.org","thesmarterbusiness.com",
			"thfox.com","thingthingarena32.com","thisislifeschool.com","thisismarilyn.com","threelions.no","threelollies.com",
			"thunderboy.de","thurrockfestival.co.uk","tienganhdeec.com","tinyfi.com","tinyurl.cf","tinyurl.us","tiristor.ru",
			"tistory.com","tnscg.com","tobie.fr","toc.hk","todoalmejorprecio.es","todofierro.com.ar","tok2.com","tokio19.ru",
			"topenk.com","topmodel.it","topmodelspiele.com","torontocomputertech.com","torrevieja.com","totalbrest.com",
			"towerdefense.me","toysrus.com","tppm.by","trainbasketball.info","trainplace.com.au","transeffect.com",
			"travelsdk.com","tribhaktialhusna.com","tribu.red","triport.ru","tropicafarms.in","trovit.com","trucktv.eu",
			"tsbank.ru","tty.nu","tulsa.eu","tumblr.com","turningturning.com","tuskar.by","tut3d.com","tut.su",
			"tz-valeo.com","ucla.edu","udm4.com","uduroc.com","uiucnopants.com","ukksm.ru","ukrdomen.com","ulmf.org",
			"ultra-joy.com","uluv.us","ummulqurodepok.com","underconstructiondayz.co.uk","ungthuphoi.info","unisew.co.uk",
			"uniteldirect.co.uk","universitywebguide.com","uniwearmoda.com","unjubilado.info","unterleider-strassenbau.de",
			"un-wiredtv.com","upr.edu","upstaresclub.com","upupplease.org","urbanexplorationsquad.be","urbanomx.com",
			"url.bz","usasexguide.info","useurl.net","usi.ch","usk.ru","utm.my","uvleddetector.com","v8-rental.com",
			"valacro.eu","vapewiki.com","vasta.in","vegan-victory.de","vegasystems.com","vendesanfrancisco.com.ar",
			"v.gd","villagefloorcovering.biz","viralsections.com","virgendefatima.es","vivicreators.com","vlcg.net",
			"vivremerpheecotravel.com","vladit.ru","voidstar.com","vokr.com","volgomotolom.ru","voloclubfenice.com",
			"volty.com","vsil.org","vurl.us","wall-c.com","wallpapereye.com","wandagaghouse.org","wandern-im-winter.ch",
			"wapic.org","warp2games.com","way2blue.com","wcpss.net","webbyline.com","webcams.is","webcis.com","web.gi",
			"web-directory.mobi","webgains.com","webhostingtalk.com.es","webkinzinsider.com","webmdbook.com","webnow.biz",
			"webproworld.com","webru.biz","websitehome.co.uk","weeklysports.co.uk","wellnesswithmary.com","wemakesites.net",
			"whackyourboner.com","wheresweems.com","whiskeyinkandlace.com","whynotsport.com","wickedskills.com","wikipartido.es",
			"wilforum.com","williamlevygutierrez.com","winfarmer.it","cncpunishment.com","coches.net","cloudfront.net",
			"wirednewyork.com","wo.lt","womonology.ru","wonosarigek.com","woodgreencompanyltd.com","wshworld.de","wyndia.com",
			"wz.cz","xd03.com","xed.cc","xmagz.com","xn----ctbj0bbmbku.xn--p1ai","xn--h1aehhjhg.tv","xoxo-charm.com",
			"xqno.com","xxfuq.com","yahvlane.com","yatricar.com","yawarperu.com","yawenedu.com","ykuwait.net",
			"youtube.com","youtubeklipindir.com","ypim.com.au","yuctw.com","yunikoo.net","yuntj.com","yz888.cn","zacbird.com",
			"zanettiterrazzo.com","zanox.com","zepyur.am","zhkdesign.com","zhp.pl","zipcodeflea.com","zoohome.ru","zupaa.com",
			"zvonite-darom.ru","360overseas.com","3x.ro","acpasion.net","adelement.com","cliclogix.com",
			"affordableturnkeywebsites.com","aim4media.com","aippc.net","alternatehistory.com","altervista.org","antichat.net",
			"as-salud.com","automaniasiouxfalls.com","azdeals.co.uk","azfj.org","bathandbodyworks.com","bestbuy.com",
			"bestfilms.eu","bezpaleva.ru","blitwise.com","blogspot.com","blogspot.pl","boholbeefarm.com","botecodoilgo.com.br",
			"braingamesnyc.com","brcdn.com","bycontext.com","byethost12.com","caesaremnostradamus.com","carmonix.com.br",
			"carrom.com","cbslocal.com","chatloungebb.com","cherokeecounty-nc.gov","choicestream.com","chuhal.mn",
			"cohnwolfe.it","colortranny.com","com-central.net","com-claimprize.co","company-target.com","com.vn","com-ytu.co",
			"dessertsbydana.mobi","detikone.com","dodgetech.com.ar","domaincrawler.com","dpclk.com","ducandnhung.com",
			"eab.com","edu.co","edu.pl","edu.tw","eheli.at","elearninggame.com","emporiodomedicamento.com.br","exvagos.com",
			"fastclick.net","fcpfindonesia.org","ferramentaerrico.com","firstgreatexpedition.org","florida-links.de",
			"forexvideofactory.com","forojovenes.com","free.fr","friendsinwar.com","froeschle-design.de","funzoneatlanta.com",
			"goodgamestudios.com","gpm-digital.com","gusrilkenedi.com","hackergames.net","hentaigiant.com","hollisterco.com",
			"hopurls.net","howardforums.com","inkfilling.com","intelliad.de","internationalsexguide.info","ismyblogworking.com",
			"jcdanceco.com","jd.com","jobrapido.com","jobui.com","jogger.pl","johnfoeh.com","kerbalspaceprogram.com","kiev.ua",
			"kingsriverfisheries.org","legalbeagles.info","llow3339.com","lovelytrannys.com","luennemann.org","mayanrocks.com",
			"mbzclan.com","mediaoptout.com","microgames.fr","militaryphotos.net","mohdrafi.com","mostpopularwebsites.net",
			"mulka.net","mypangandaran.com","nazarov.net","ne.jp","nelmax.de","net.br","nihonmura.com","nz-hotrod.com",
			"officedepot.com","openlinksw.com","oraculodenostradamus.com","pageinsider.com","paleodietrecipes.website",
			"panoramio.com","payson.se","pinoyexchange.com","pixies-place.com","planetsuzy.org","pornsticky.com","psykeout.net",
			"puertasdominador.com","quisma.com","rebootwithjoe.com","reedsmith.com","remodelnet.com","researchgate.net",
			"rosegaspar.org","rseramedika.com","rtbserver.com","sab-fm.de","salon.by","sat-sharing.info","schoolhistory.co.nz",
			"sci.io","sensog.com","sfdpw.org","sharethis.com","shpplug.in","smowtion.com","stackadapt.com","stingraybeachinn.com",
			"sunstargames.com","tagsrvcs.com","techkrait.ru","thrixxx.com","tiffanysurabaya.com","todomarino.com","travelzad.com",
			"trophee-roses-des-sables.com","tv3.cat","url2s.nl","usasexguide.info","uw.edu","vipnetservices.com",
			"voluumtrk.com","weavrs.info","webs.com","xingcloud.com","yoreparo.com","zeroent.net","zmievski.org","26l.mobi",
			"acuityplatform.com","altrooz.com","ancestry.com","aomaot.com","appspot.com","blogdrauf.de","blogspot.com.es",
			"ca.us","ccgoldenretriever.com","ciberwatch.es","com.cn","com.co","dotomi.com","edu.ve","etgdta.com","fiuxy.com",
			"futboltk.com","htcmania.com","inthenowweddings.com","kellythomasdesigns.com","ku6.com","markettamer.com",
			"maxlab.ru","mestreafiliados.com","neoshoforums.com","org.tw","org.ua","pardot.com","promotools.biz","taobao.com",
			"tvb.com","wiyaphotos.com","xad.com","zen-cart.com","americanpreppersnetwork.com","appflood.com","apsalar.com",
			"fronthousepictures.com","faffcamp.com","fairytaleglitter.bloggplatsen.se","fannys.bloggplatsen.sefannys.bloggplatsen.se",
			"faq.adsika.com","fedoraforum.org","felicahuggins4.postbit.com","felicidadesemgluten.com.br","fetfreaks.co.uk",
			"fiftytb.com","filestream.org","firewall.lv","firmstyle.net","firsturl.de","fisioterapi.univrab.ac.id",
			"fitness-plans-for-women-florence.com","flash.zeidanphy.com","floraindah.web44.net","florenew72243.postbit.com",
			"foro.kumbiaphp.com","foro.libertaddigital.tv","foro.lost-wow.info","foros.arquinauta.com","foro.seprin.com",
			"foros.expansion.com","fortworthtms.mobi","forum2.unitrends.com","forum.bomoo.com","forum.cs1cafe.com",
			"forum.debatarian.com","forum.faak.ru","forum.flightradar24.com","forum.garpy.info","forum.heismarried.com",
			"forum.ionitcom.ru","forum.jowood.com","forum.keypublishing.co.uk","forum.mennigmann.com","forum.n-sk.info",
			"forum.oqoasis.com","forum.praxisbase.com","forums.allaboutjazz.com","forums.eagle.ru","forums.loquax.co.uk",
			"forums.mydigitallife.info","forums.naughty-seduction.net","forums.qlshifi.com","forums.sagetv.com",
			"forums.thepaceline.net","forums.wtfda.org","forum.t-tapp.com","forum.vyos.net","forum.zohur14.com",
			"foto-biysk.ru","wap.xxmmhh.net","jnpt.jp","pinterest.com","kaiyunholding.com","bernco.gov","cathedralcity.gov",
			"miguelarino.com","dustinstockton.com","wilbooks-literacy-partners.com","majavidmar.com","telesentinel.com",
			"ilcerchiomagico.net","gsselular.com","u39414.netangels.ru","abcworshiparts.org","brainboost.tv","cipo.cl",
			"janemcqueen.com","thefullyield.com","novotyr.edu22.info","wiki.ustea.org","shufflespot.webcrow.jp",
			"tennisgrandstand.com","to-bi.jp","tikiplay.com","club.thairentacar.com","studio.chance-magazine.com",
			"srilankanbesttravels.com","mffcu.org","petrotechgroups.com","smpdh.com","tracker.affiliate.media.net",
			"fredericlaprise.com","counter.arabamoto.com","uasdan.com","tku.edu.tw","honeymoonbroadway.com",
			"urlshotgun.zendesk.com","andersonlanham6.bligoo.com","protect.downloadiz2.com","chicagorehab.net","pa-kudus.go.id",
			"studio-one-touch.ru","ldbs.foxdevel.com","kireenko.by","benjaminbos.nl","tragaperras777.com","weightlosstipstv.com",
			"pvt.prv.pl","damle.org","mccleto.com","hosei-im.jp","juigames.com","teknisk-brevkasse.dk","fastsync.de",
			"ironmanhawaii.de","8game.ir","guabob.com","donorcall.com","outpostbravo.com","g-javierortega.newsvine.com",
			"keygroupinternational.com","svendemeyere.write2me.nl","hksnv.fksnv.sk","cityprepsports.com",
			"bjhdjj.com.cn","chiefhudson.com","southseattlecrossfit.com","bazisun.ir","office-board.net","onlinesocial.ru",
			"memphis-tn.com","guestbook.redravenllc.com","foodspotting.com","middelhavetsperle.com","pvt.prv.pl",
			"harrietsellingblog.com","visioncenterslv.com","altai.aif.ru","cqumzh.cn","rsud.wonosobokab.go.id",
			"dynamod.com","simplebrunchideas.com","knopa-lepa.ru","ksaemarket.com","cqumzh.cn","damle.org",
			"gburugburuwins.org","agimato.crystalstar.me","ginki.it","findyourway.in","serralheriaght.com.br",
			"gadgetvlog.com","gwearn.com","gamerstvspot.com","wikiova.com","u39414.netangels.ru","mundoambiente.com.br",
			"eu.purefishing.com","lankaeuro.info","atrophythemovie.com","bildergeburtstag.com","cts.businesswire.com",
			"bkxiaoyu.com","en.eelink.com.cn""bmu.fr","rebelmouse.com","lulle.sakura.ne.jp","trustinsurance.co.uk",
			"pa-kudus.go.id","studio-one-touch.ru","kireenko.by","benjaminbos.nl","tragaperras777.com","weightlosstipstv.com",
			"juigames.com","fotocasa.es","blacdetroit.com","consumeractiongroup.co.uk","romwe.com","bbs.whu.edu.cn",
			"productads.hlserve.com","tudocelular.com","apps.lonestar.edu","crossfit128.com","org.idv.tw","northdallaseo.com",
			"thechangesource.com","sabceducation.com","cafekazan.com","jogos.connectvr.com","dudyeffendy.com",
			"flat.ciseleur.com","c4mountainbike.com","lechfeld-lamas-alpakas.de","tssj.cl","cpoar.org","frozenfood.ru",
			"biocenterortodoncia.com","uzin.com.ua","geologopatelli.it","mobimeasure.co.za","mobyleapps.com",
			"tipseri.org","mini-juegos.net","grapplingtournaments.com","hackermeetup.com","ebooks.addall.com",
			"external.worldbankimflib.org","cathedralcity.gov","cops.usdoj.gov","bekamsehat.com","cqumzh.cn",
			"altai.aif.ru","polytrauma.va.gov","fateh.sikhnet.com","legix.pt","aif.ua","louisiana.gov","expert.ru",
			"cqumzh.cn","gettyimages.fr","tinyurl.com","altai.aif.ru","polytrauma.va.gov","ferra.ru","dineroforo.com",
			"big5.shanghai.gov.cn", "demonoid.pw","res-x.com","kartes.lv","estetica-design-forum.com",
			"bauskasdzive.diena.lv","unimedfesp.coop.br","flix360.com","254a.com","ksmobile.net","cnt.my",
			"mmstat.com","gfy.com","flixcar.com","ekspedisicepat.com", "turk-bh.ir","alenty.com","gandhi.com.mx",
			"exelator.com","fitfuel365.com","popjustice.com","inverly.com", "badoocdn.com","contextweb", 
			"technoratimedia.com","youku.com","autoscout24.com","forumodua.com","fronthousepictures.com"]
		@disconnect,@sameParty=loadExternalFilter(external) if external!=nil
	end

	def loadExternalFilter(external)
		@defines.puts "Loading external Blacklist..."
       	file = File.read(external)
       	json = JSON.parse(file)
        cats=json['categories']
       	filter=Hash.new
        for cat in cats.keys do
                cats[cat].each{ |subCats| subCats.each {|key,values|
                        values.each { |val| val.each{ |doms| (doms.each{|k| filter[k]=cat+"#"+key}) if not doms.is_a?(String)}}}}
        end
#       filter.each {|key,value| puts key+" "+value.to_s}
		sameParty=Hash.new(nil)
		cats.keys.each{|cat| cats[cat].each {|array| array.each{ |company, sites| sites.each{|head, list| list.each{|elem| 
			if sameParty[cat]==nil
				sameParty[cat]=Hash.new 
			end
			sameParty[cat][elem]=head}}}}}
        return filter,sameParty
    end
end
